### ISSUE TITLE
Why dropped support for Carthage?

### ISSUE THREAD

**Issue by cezheng** [kylef/Commander#13]
I noticed that the xcodeproj along with the shared schemes are deleted in a recent commit(https://github.com/kylef/Commander/commit/992625726100e24656716a919fdd1645a9557b0b), but the current Readme still says Carthage is supported. Is it an accident or do we have to give up Carthage if we would like to get the latest version from now on?

I'm currently developing a command line tool and I personally prefer the submodule way of managing dependencies, which is provided by Carthage. 

Conche is good, but it is not the right choice for me since I'm using a Xcode project and packed all resources into an app bundle. Using Cocoapods & Carthage together is definitely a mess, so I really hope you could bring back the xcodeproj along with the shared schemes. Otherwise it should be painful in case Swift's next update breaks Commander and I have to constantly sync all the new commits from this repo to my fork.

Thank you.

**Comment by kylef** [comment]
Sorry about this @cezheng, I forgot to update the README when I removed the Xcode project.

I'll try and restore Carthage support soon, please give me a few days to finish this.

**Comment by kylef** [comment]
Given the recent announcement of SPM (Swift Package Manager), I no longer have any intentions of adding Carthage support. Going to close this one out.

**Comment by neonichu** [comment]
👍
