### ISSUE TITLE
Release notes missing for latest releases

### ISSUE THREAD

**Issue by AliSoftware** [kylef/Commander#15]
And no CHANGELOG either :stuck_out_tongue_winking_eye:

**Comment by AliSoftware** [comment]
@kylef ping — I'm willing to upgrade but don't know if that'll break the API or if I got new features I could adopt (like subcommands summary/description :wink:)

**Comment by kylef** [comment]
This is done: https://github.com/kylef/Commander/releases/tag/0.3.0
