### ISSUE TITLE
`command` should be a type, not a function

### ISSUE THREAD

**Issue by Ahti** [kylef/Commander#20]
I think `command` should be made a type, so we'd write `Command` instead.

This is more consistent with `Option` and `Command`.

I also think with how it is now, it's not very clear that this block of code:

```
command {

}
```

does not actually execute anything.

**Comment by kylef** [comment]
There is already a [CommandType](https://github.com/kylef/Commander/blob/master/Sources/CommandType.swift#L2), the `command` function is a convenience wrapper around the [`AnonymousCommand`](https://github.com/kylef/Commander/blob/master/Sources/Command.swift).

The `command` function does not annotate the closure as `noescape`, so to me it's absolutely clear it doesn't execute the closure immediately. Take a look at the [swift documentation on `noescape`](https://developer.apple.com/library/ios/documentation/Swift/Conceptual/Swift_Programming_Language/Attributes.html):

> Apply this attribute to a function or method declaration to indicate that a parameter will not be stored for later execution, such that it is guaranteed not to outlive the lifetime of the call.

There is multiple variants of the `command` function to take N arguments. Having multiple different different types would be very cumbersome and not very intuitive for users.

```swift
/// Create a command which takes 1 argument using a closure
public func command<A:ArgumentConvertible>(closure:(A) throws-> ()) -> CommandType {
  return AnonymousCommand { parser in
    try closure(try A(parser: parser))
  }
}

/// Create a command which takes 2 argument using a closure
public func command<A:ArgumentConvertible, A1:ArgumentConvertible>(closure:(A, A1) throws-> ()) -> CommandType {
  return AnonymousCommand { parser in
    try closure(try A(parser: parser), try A1(parser: parser))
  }
}

/// Create a command which takes 3 argument using a closure
public func command<A:ArgumentConvertible, A1:ArgumentConvertible, A2:ArgumentConvertible>(closure:(A, A1, A2) throws-> ()) -> CommandType {
  return AnonymousCommand { parser in
    try closure(try A(parser: parser), try A1(parser: parser), try A2(parser: parser))
  }
}

/// Create a command which takes 4 argument using a closure
public func command<A:ArgumentConvertible, A1:ArgumentConvertible, A2:ArgumentConvertible, A3:ArgumentConvertible>(closure:(A, A1, A2, A3) throws-> ()) -> CommandType {
  return AnonymousCommand { parser in
    try closure(try A(parser: parser), try A1(parser: parser), try A2(parser: parser), try A3(parser: parser))
  }
}
```
