### ISSUE TITLE
Deprecation warning: ++ is deprecated

### ISSUE THREAD

**Issue by BlakeLucchesi** [kylef/Commander#21]
There are some deprecation warnings received when compiling the Commander package with the latest version of Swift 2.2-dev Feb 3, 2016.

` warning: '++' is deprecated: it will be removed in Swift 3`

```
Sources/ArgumentParser.swift:121:9
Sources/ArgumentParser.swift:163:7
Sources/ArgumentParser.swift:189:7
Sources/ArgumentParser.swift:214:9
```

**Comment by BlakeLucchesi** [comment]
Sorry, I did not notice that this was already fixed in master. Do you think it warrants tagging a new release 0.4.1?

**Comment by kylef** [comment]
I don't think removing a warning for a snapshot of Swift is warrants an additional release.
