### ISSUE TITLE
Deprecation warning: use of 'typealias' to declare associated types is deprecated

### ISSUE THREAD

**Issue by BlakeLucchesi** [kylef/Commander#22]
I received the following complier warnings while building the Commander package.

`warning: use of 'typealias' to declare associated types is deprecated; use 'associatedtype' instead.`

```
Sources/ArgumentDescription.swift:7:3
```

**Comment by BlakeLucchesi** [comment]
Here is a full explanation of the typealias/associatedtype change from the swift evolution proposals:

https://github.com/apple/swift-evolution/blob/master/proposals/0011-replace-typealias-associated.md

**Comment by BlakeLucchesi** [comment]
PR #23

**Comment by kylef** [comment]
This has been resolved.
