### ISSUE TITLE
Please release 0.4.1

### ISSUE THREAD

**Issue by czechboy0** [kylef/Commander#24]
I encountered the crash fixed in #18. Instead of reporting an unknown command, Commander crashes.

**Comment by kylef** [comment]
Made the [CI run on Linux](https://github.com/kylef/Commander/commit/13ff7ae41acab9c296d8b73d883a9b0b9cf24012#diff-354f30a63fb0907d4ad57269548329e3R2) to prevent these kind of problems coming up in the future. I've also made the [0.4.1 release](https://github.com/kylef/Commander/releases/tag/0.4.1).
