### ISSUE TITLE
how do i use it with cart file

### ISSUE THREAD

**Issue by gabhi** [kylef/Commander#26]
I tried adding 

`github "Kylef/Commander"` but didn't help.

What is the proper way to use commander with Cartfile?

**Comment by kylef** [comment]
Commander does not support Carthage, you can use any of the installation methods mentioned in the [README](https://github.com/kylef/Commander#installation).

Swift Package Manager being the recommended approach.

**Comment by gabhi** [comment]
thanks @kylef . It would have been nice if it had supported Cartfile.

**Comment by cezheng** [comment]
Yeah, simply because the SPM sucks terribly at the moment, many of us have no choice but stick to Carthage. For anyone who still wish to use Carthage, use version 0.2.2, or fork it and create a xcodeproj for it.
