### ISSUE TITLE
Flag constructor arguments order isn't consistent with Option

### ISSUE THREAD

**Issue by robertjpayne** [kylef/Commander#35]
The Flag constructor takes `default` as the last argument where as Option takes it as the second argument.

When using both in a single command it's a bit weird to have:

```
Flag("web", description: "Whether or not to search the web", default: false),
Option("remote", "cocoapods.org", description: "Custom remote host"),
```

**Comment by kylef** [comment]
The arguments have been aligned in Commander 0.8.0.
