### ISSUE TITLE
Add badges

### ISSUE THREAD

**Issue by TofPlay** [kylef/Commander#47]
Below the title please add badges this help a lot. 

If your component is compatible: 
- with carthage add [![Carthage compatible](https://img.shields.io/badge/Carthage-compatible-brightgreen.svg)](https://github.com/Carthage/Carthage)
- with SwiftPM add [![SwiftPM compatible](https://img.shields.io/badge/SwiftPM-compatible-brightgreen.svg)](https://github.com/apple/swift-package-manager)

Indicated:
- the Swift version ![Swift Version](https://img.shields.io/badge/Swift-3.0-orange.svg)
- Platforms supported ![Plaforms](https://img.shields.io/badge/Platforms-Linux%20%7C%20macOS%20%7C%20iOS%20%7C%20WatichOS%20%7C%20tvOS-lightgrey.svg)
- License ![License MIT](https://img.shields.io/badge/License-MIT-lightgrey.svg)

**Comment by kattrali** [comment]
Badge proliferation makes this information harder to parse in an accessible way, such as using screen readers or even in a pager/vim. READMEs should be readable.

**Comment by TofPlay** [comment]
@kattrali When we search for a component or tool on GitHub we have the choice among several possible choices. We must then select the one that best fits our needs. The badges immediately allow us you to see if a component can fit with our technical environment. Integrating a badge does not make it less readable README.md. When searching for a component or tool, it takes no more than few seconds to read README.md. Without the badges there is a greater risk that the component will not be retained.
