### ISSUE TITLE
Option without default value

### ISSUE THREAD

**Issue by fikovnik** [kylef/Commander#49]
Is it possible to specify an option without default value?
I might be missing something, but it seems that the default value is mandatory. While I can set it to some magic value, the problem is that it is printed using the "[default: XXX]" in help.

**Comment by kylef** [comment]
Once #42 is merged I'll add this feature request.

**Comment by kylef** [comment]
This is possible via using `Options` and providing an empty array as the default value:

```
$ swift run Example
Hello

$ swift run Example --name kyle
Hello kyle

$ swift run Example --help
Usage:

    $ .build/x86_64-apple-macosx10.10/debug/Example

Options:
    --name
```

```swift
import Commander

command(
  Options<String>("name", default: [], count: 1)
) { name in
  if let name = name.first {
    print("Hello \(name)")
  } else {
    print("Hello")
  }
}.run()
```
