### ISSUE TITLE
0.7.1 doesn't build on linux

### ISSUE THREAD

**Issue by valeriomazzeo** [kylef/Commander#56]
Cause:
https://bugs.swift.org/browse/SR-5627

Travis:
https://travis-ci.org/kylef/Commander/jobs/280842533

**Comment by kylef** [comment]
Ah, I did not realise that was failing. Should be trivial to work around. I don't have much free time to do it right now. Feel free to submit a PR if you would like to get this moving quicker and I can make a patch release.

Should be able to do something similar to https://github.com/kylef/Commander/commit/6a84178b35fb25f05aa3ed541e14168994fe85f0#diff-66a8f5155af4ac7e1f02c996a0d61f34L55

**Comment by kylef** [comment]
This has been fixed in Commander 0.8.0.
