### ISSUE TITLE
Using the argument parser

### ISSUE THREAD

**Issue by lucabartoletti** [kylef/Commander#60]
Hi,

I'm trying to determine if the command is receiving a specific command.
I saw this example in README, Is this still valid?

```
command { (name:String, parser:ArgumentParser) in
  if parser.hasOption("verbose") {
    print("Verbose mode enabled")
  }

  print("Hello \(name)")
}
```

Probably I'm missing something here, but as far I can understand looking to `Command.swift` the parser is never passed to the `closure` as parameter.
Is there another way to do what I'm trying to achieve without accessing the parser?

**Comment by kylef** [comment]
> Probably I'm missing something here, but as far I can understand looking to Command.swift the parser is never passed to the closure as parameter.

The `ArgumentParser` is `ArgumentConvertible` so it can always be access via specifying a parameter of the `ArgumentParser` type as that conforms to `ArgumentConvertible`. As mentioned in the NOTE above that example.

> I'm trying to determine if the command is receiving a specific command.
> Is there another way to do what I'm trying to achieve without accessing the parser?

Not entirely clear to me what you are trying to do. Are you trying to make a group with different subcommands? If so check out the [grouping example](https://github.com/kylef/Commander#grouping-commands).

```swift
Group {
  $0.command("login") { (name:String) in
    print("Hello \(name)")
  }

  $0.command("logout") {
    print("Goodbye.")
  }
}
```

If you want to receive an argument and do whatever you want with it manually that can be done via just receiving an argument:

```swift
command(
    Argument<String>("command", description: "...")
) { command in
  if command == "foo" {
    print("argument foo was provided")
  }
}.run()
```

**Comment by lucabartoletti** [comment]
I'm sorry if my need was not clear enough.

My need is that for this example

```
    command(
        Flag("verbose",
             flag: "v",
             description: "Turn on verbose logging"),
        Option<Path>("output", ".", description: "Output path."),
    ) { verbose, output in
           
    }
```

I want to know if the user passed any parameter or not.

As far as I understand the verbose is always defined (not being optional), so if the user run the command as 

`commandname` without any parameter, the `verbose` parameter gets is default value.
How can I differ this two cases?

`commandname`
`commandname --verbose`
