### ISSUE TITLE
Commander Package.swift --> targets error

### ISSUE THREAD

**Issue by devM4x** [kylef/Commander#61]
Hi, wtf? 

i got error when try using in terminal 

go to folder with project, adding repo to Package.swift 
go to terminal --> swift build and got error 

`
Desktop:cryptpwd username$ swift build
warning: refname '0.8.0' is ambiguous.
warning: refname '0.8.0' is ambiguous.
HEAD is now at e5b50ad chore: Release 0.8.0
Resolved version: 0.8.0
/Users/username/Desktop/cryptpwd/Packages/Commander/Package.swift:13:3: error: argument 'targets' must precede argument 'dependencies'
  targets: [
  ^
Can't parse Package.swift manifest file because it contains invalid format. Fix Package.swift file format and try again.
error: The package at `/Users/username/Desktop/cryptpwd/Packages/Commander' has no Package.swift for the specific version: 0.8.0
`

**Comment by devM4x** [comment]
fixed by use a version 6 
.Package(url: "https://github.com/kylef/Commander", majorVersion: 0, minor: 6),

**Comment by kylef** [comment]
Are you using Swift 4?
