### ISSUE TITLE
Printing the default value of a string enum?

### ISSUE THREAD

**Issue by jum** [kylef/Commander#62]
I am using the following enum as an argument:

```swift
enum SyncSource: String, ArgumentConvertible {
	case finder
	case iptc
	case both

	public init(parser: ArgumentParser) throws {
    if let value = parser.shift() {
		if let value = SyncSource(rawValue: value) {
			self.init(rawValue: value.rawValue)!
		} else {
			throw ArgumentError.invalidType(value: value, type:"SyncSource", argument: nil)
		}
    } else {
		throw ArgumentError.missingValue(argument: nil)
    }
  }
  public var description: String {
	  return self.rawValue
  }
}
```

Even though I did implement description I do not get a default value printed for a SyncSource option declared like this:

```swift
	Option("source", default: SyncSource.both, description: "Sync attributes source \([SyncSource.finder.rawValue, SyncSource.iptc.rawValue, SyncSource.both.rawValue])"),

```

**Comment by kylef** [comment]
Hi @jum, I've added support for this in cfbcb29. Could you give it a go and ensure it is working for you?

**Comment by jum** [comment]
I am a bit of still learning the swift package manager, but I appear not to be able to update to the latest HEAD, the package manager insists on checking out the 0.8.0 version. Any hint how I can convince it to use the latest HEAD?
--
Jens-Uwe Mager  <pgp-mailto:D5D75498>
