### ISSUE TITLE
Cannot define an argument named `version`

### ISSUE THREAD

**Issue by ileitch** [kylef/Commander#79]
Defining a `version` argument appears to conflict with some internal definition.

Given the argument:
```swift
Option<String?>(
    "version",
    default: nil,
    description: "The version number of the build"),
```

Commander always fails to parse the value:

```
$ mytool mycmd --version 123
Unknown Arguments: 123
```

**Comment by kylef** [comment]
`--help` and `--version` are currently reserved options which already have defined behaviour. (https://github.com/kylef/Commander/blob/314f8d7455e25e60e9e9b850040eebd0a87f2527/Sources/Commander/CommandRunner.swift#L14). It might be worth considering renaming your option from `--version` because traditionally `--version` returns the version of the command which is consistent with many other tools:

```
$ git --version
git version 2.21.0

$ swift --version
Apple Swift version 5.1 (swiftlang-1100.0.270.13 clang-1100.0.33.7)
Target: x86_64-apple-darwin18.7.0

$ curl --version
curl 7.54.0 (x86_64-apple-darwin18.0) libcurl/7.54.0 LibreSSL/2.6.5 zlib/1.2.11 nghttp2/1.24.1
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: AsynchDNS IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz HTTP2 UnixSockets HTTPS-proxy

$ swiftenv --version
swiftenv 1.4.0

$ brew --version
Homebrew 2.1.12-16-ge407da3
Homebrew/homebrew-core (git revision d61aef; last commit 2019-10-07)
Homebrew/homebrew-cask (git revision d8b7f; last commit 2019-10-07)

$ pod --version
git 1.8.1

$ xcodebuild -version
Xcode 11.0
Build version 11A420a
```

Users would often expect `--version` to return the version of the command like it would for almost all CLIs.

**Comment by kylef** [comment]
Given the domain, perhaps `--build <INT>` would be more intutive users instread of `--version <INT>`

**Comment by ileitch** [comment]
Agreed that `--version` is expected behavior for the top-level command, however for a sub command I'd argue that it is unexpected. At least, I wasn't expecting it 🙃. Perhaps at least Commander should produce an error when a reserved argument is declared?

**Comment by kylef** [comment]
You could play around with this diff to make the default handling of `--version` go away if `version` isn't provided to run:

```diff
diff --git a/Sources/Commander/CommandRunner.swift b/Sources/Commander/CommandRunner.swift
index c421853..c8e74ac 100644
--- a/Sources/Commander/CommandRunner.swift
+++ b/Sources/Commander/CommandRunner.swift
@@ -11,11 +11,9 @@ extension CommandType {
   public func run(_ version:String? = nil) -> Never  {
     let parser = ArgumentParser(arguments: CommandLine.arguments)
 
-    if parser.hasOption("version") && !parser.hasOption("help") {
-      if let version = version {
-        print(version)
-        exit(0)
-      }
+    if let version = version, parser.hasOption("version") && !parser.hasOption("help") {
+      print(version)
+      exit(0)
     }
 
     let executableName = parser.shift()!  // Executable Name
```

I'm not against changing this if that works out. Feel free to pull request it in if its helpful for you.

---

> Agreed that --version is expected behaviour for the top-level command, however for a sub command I'd argue that it is unexpected

Commander attempts not to make a distinction of options/flags at different levels. I find this particular behaviour cumber some in other command line interfaces. As a user this behaviour is frustrating, causing the user to be very particular about where the option goes in the argument list.

```bash
# won't work, config MUST be set at a previous level
$ auther token generate kyle --config config.toml
Usage: auther token [OPTIONS] COMMAND [ARGS]...

Error: Invalid value for config: Missing configuration
```

```bash
# won't work, config not set at global command only token group
$ auther --config config.toml token generate kyle
Usage: auther [OPTIONS] COMMAND [ARGS]...
Try 'auther --help' for help.

Error: no such option: --config
```

```bash
# yeah thats it
$ auther token --config config.toml generate kyle
ey...
```
